### ISSUE TITLE
[WIP] Track the progress of PIP-149-Making the REST Admin API fully async

### ISSUE THREAD

**Issue by mattisonchao** [apache/pulsar#15043]
### Motivation

This issue is used to track the progress of [PIP-149 Making the REST Admin API fully async](https://github.com/apache/pulsar/issues/14365).

**We should check this PIP first to know our purpose and then push PR to refactor.**

**Each group, consisting of 2~4 methods, referring to the rules of [PIP-149](https://github.com/apache/pulsar/issues/14365) to submit only one patch to fix.**

#### BrokersBase
- [x] `getOwnedNamespaces`/`getAllDynamicConfigurations`/`getDynamicConfigurationName` @mattisonchao  https://github.com/apache/pulsar/pull/15280
- [x] `getRuntimeConfiguration`/`getInternalConfigurationData`/`backlogQuotaCheck`@mattisonchao https://github.com/apache/pulsar/pull/15281

#### ClustersBase
- [x]  `getClusters` /  `getCluster` /  `createCluster` / `updateCluster` @mattisonchao https://github.com/apache/pulsar/pull/15318
- [x] `setPeerClusterNames` / `getPeerCluster` / `deleteCluster` @mattisonchao https://github.com/apache/pulsar/pull/15358
- [x] `getNamespaceIsolationPolicies` / `getNamespaceIsolationPolicy` / `getBrokersWithNamespaceIsolationPolicy` @mattisonchao https://github.com/apache/pulsar/pull/15437
- [x] `getBrokerWithNamespaceIsolationPolicy` / `setNamespaceIsolationPolicy`  @mattisonchao  https://github.com/apache/pulsar/pull/15527
- [x] `deleteNamespaceIsolationPolicy` /  `setFailureDomain` / `getFailureDomains` @mattisonchao #15685
- [x] `getDomain`/ `deleteFailureDomain` @mattisonchao  https://github.com/apache/pulsar/pull/15847

#### Namespaces
- [] `deleteNamespace` @mattisonchao
- [x]  `getTenantNamespaces` /  `createNamespace` /   @Technoboy-  https://github.com/apache/pulsar/pull/15518
- [x]  `getTopics` /  `getPolicies` /  `getPermissions` @Technoboy-  https://github.com/apache/pulsar/pull/15518
-  [x]  `getPermissionOnSubscription` /  `grantPermissionOnNamespace` /  `grantPermissionOnSubscription`  #16324
-  [x]  `revokePermissionsOnNamespace`  / `revokePermissionOnSubscription` #16324
- [x]  `getNamespaceReplicationClusters` /  `setNamespaceReplicationClusters` @shibd  #15760
- [x]  `getNamespaceMessageTTL` /  `setNamespaceMessageTTL` / `removeNamespaceMessageTTL` @shibd #15577
- [x]  `getSubscriptionExpirationTime` / `setSubscriptionExpirationTime` / `removeSubscriptionExpirationTime` @shibd #16328 
- [x]  `getDeduplication` / `modifyDeduplication` / `removeDeduplication` @shibd #15608
- [x]  `getAutoTopicCreation` / `setAutoTopicCreation` / `removeAutoTopicCreation` @shibd #15621
- [x]  `setAutoSubscriptionCreation` / `getAutoSubscriptionCreation` / `removeAutoSubscriptionCreation` #16329 @shibd 
- [x]  `getBundlesData` / `unloadNamespace` / `unloadNamespaceBundle` @shibd 
- [x]  `splitNamespaceBundle` / `getTopicHashPositions` / `setPublishRate` @leizhiyuan
- [x]  `removePublishRate` / `getPublishRate` / `getDispatchRate` /  `setDispatchRate` / `deleteDispatchRate` @zhangqian321 #15946
- [x]   `setSubscriptionDispatchRate` /  `getSubscriptionDispatchRate` / `deleteSubscriptionDispatchRate`  @gaoyanliang  #15880
- [x]  `deleteSubscribeRate` / `setSubscribeRate`  / `getSubscribeRate`  @gaoyanliang #15656

#### Tenants
- [x]  `getTenants` /  `getTenantAdmin` / `createTenant` / `updateTenant` / `deleteTenant` @Technoboy- #15603

#### ResourceQuotas
- [x]  `getDefaultResourceQuota` /  `getNamespaceBundleResourceQuota` / `setNamespaceBundleResourceQuota` / `removeNamespaceBundleResourceQuota` @Technoboy- #15605

#### SchemasResource
- [x]  `getSchema` /  `deleteSchema` / `postSchema` / `getVersionBySchema` / `testCompatibility` @Technoboy-  #15821

**Comment by gaoyanliang** [comment]
I'll take care of （Namespaces - deleteSubscribeRate / setSubscribeRate / getSubscribeRate）, please assign to me

**Comment by gaoyanliang** [comment]
<img width="862" alt="image" src="https://user-images.githubusercontent.com/33021341/170919640-e0b89633-9c10-4765-89e5-b480094f597c.png">

please assign these tasks to me .

**Comment by leizhiyuan** [comment]
@gaoyanliang 

maybe I can help for 

```
setSubscriptionDispatchRate / getSubscriptionDispatchRate / deleteSubscriptionDispatchRate @gaoyanliang
```

**Comment by gaoyanliang** [comment]
This task will be completed soon and a review will be launched.  maybe you can help for 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/33021341/171348930-f58a2972-cfce-425d-8117-ec6bf984a3a1.png">

**Comment by zqcece** [comment]
我可以帮助完成 removePublishRate / getPublishRate / getDispatchRate / setDispatchRate / deleteDispatchRate @leizhiyuan @Technoboy- @gaoyanliang

**Comment by leizhiyuan** [comment]
> `setSubscriptionDispatchRate / getSubscriptionDispatchRate / deleteSubscriptionDispatchRate` this task has been completed, and review request has been launched. @Technoboy- @leizhiyuan @zqcece
> 
> Please @leizhiyuan @zqcece help to complete the following tasks:
> 
> * splitNamespaceBundle / getTopicHashPositions / setPublishRate
> * removePublishRate / getPublishRate / getDispatchRate / setDispatchRate / deleteDispatchRate

ok

I will work for splitNamespaceBundle / getTopicHashPositions / setPublishRate

**Comment by zqcece** [comment]
> `setSubscriptionDispatchRate / getSubscriptionDispatchRate / deleteSubscriptionDispatchRate` this task has been completed, and review request has been launched. @Technoboy- @leizhiyuan @zqcece
> 
> Please @leizhiyuan @zqcece help to complete the following tasks:
> 
> * splitNamespaceBundle / getTopicHashPositions / setPublishRate
> * removePublishRate / getPublishRate / getDispatchRate / setDispatchRate / deleteDispatchRate

thx~ i will work for removePublishRate / getPublishRate / getDispatchRate / setDispatchRate / deleteDispatchRate

**Comment by leizhiyuan** [comment]
> > `setSubscriptionDispatchRate / getSubscriptionDispatchRate / deleteSubscriptionDispatchRate` this task has been completed, and review request has been launched. @Technoboy- @leizhiyuan @zqcece
> > Please @leizhiyuan @zqcece help to complete the following tasks:
> > 
> > * splitNamespaceBundle / getTopicHashPositions / setPublishRate
> > * removePublishRate / getPublishRate / getDispatchRate / setDispatchRate / deleteDispatchRate
> 
> thx~ i will work for removePublishRate / getPublishRate / getDispatchRate / setDispatchRate / deleteDispatchRate

setPublishRate is same with these work, you can do it together

**Comment by Technoboy-** [comment]
Close as we have done all these trackings
