### ISSUE TITLE
Tracking Issue for multilingual clients document catching up

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17302]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

We have a [Client Libraries](https://pulsar.apache.org/docs/next/client-libraries) page to host all official client libraries documents. Despite the Java client's document being relatively completed, documents for multilingual clients are outdated and less maintained.

This issue tracks the effort to document what we already implemented for multilingual clients, focusing on the C++ client, the Python client, and the Node.js client - all based on the core C++ client library.

### Solution

The catching-up plan is based on:

1. [Java client's document](https://pulsar.apache.org/docs/next/client-libraries-java) for the overall structure.
2. [Feature Matrix](https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914) for what we already implemented.

#### Layout

Top-level layout (continuously updating):

* Brief introducation
* Installation
* Connection URLs
* Client
* Producer
* Consumer
* Reader
* Table View
* Schema
* Authentication

#### Common

* [x] #17303
* [x] #17307

#### C++

* [x] #17385

#### Python

* [x] #17794
* [ ] Convert handy examples to a structural layout (Client, Producer, Consumer, Reader)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@RobertIndie @shibd when you merge some patches requiring docs, you can cc me in this thread and I'm glad to track them and help on the docs side.

**Comment by tisonkun** [comment]
Closed as halted and partially delivered. We moved out the C++/Python client from the main repo, and I've worked on the API docs, which are delivered as #17917.

Sooner or later we can restructure the client library in the proposed structure above, but it will be a new turn.
