### ISSUE TITLE
[Doc] Tracking issue for incorrect contents and links

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17495]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

When I go through the document of Pulsar, I found some contents are wrong, outdated, or incomplete, and some links are incorrect or broken.

### What is your suggestion?

It happens that I have some time to work on these issues. Although, handling issues can take more time than spotting issues. 

I'd prefer to create this tracking issue for all related contents or links so all contributors can align on the current status and possibly take over some tasks.

### Contents

* [x] If you follow the [getting-started-standalone](https://pulsar.apache.org/docs/2.9.x/getting-started-standalone/) page, you won't see any message consumed because it suggests you run consume before producing a message and say that you should get a message consumed. This wart should be resolved by #17475.
* [x] #17497
* [x] Pulsar SQL document is outdated since we bump PrestoSQL version to Trino version https://github.com/apache/pulsar/pull/17798
* [x] Pulsar SQL section has a confusing [Query Your Own Data](https://pulsar.apache.org/docs/next/sql-getting-started#query-your-own-data) code snippet without any instructions. https://github.com/apache/pulsar/pull/17798
* [ ] #17498
* [ ] #17878
* [x] https://github.com/apache/pulsar/issues/17774
* [ ] https://github.com/apache/pulsar/issues/17258

### Links

See #17599.

* [ ] [/tools/pulsar-client](https://pulsar.apache.org/tools/pulsar-client/) displays confusing content, ditto [/tools/pulsar-admin](https://pulsar.apache.org/tools/pulsar-admin)
* [ ] `/api/cpp` in content rendered to SNAPSHOT document. For example, Pulsar Python client has [a link to SNAPSHOT document](https://github.com/apache/pulsar/blob/a7f1a5657782ff7ac91a89afdd49568d74d111f5/site2/docs/client-libraries-python.md?plain=1#L13). This can be related to #17498.
* [x] `/reference-configuration` should not hold [a hard link](https://github.com/apache/pulsar/blob/a7f1a5657782ff7ac91a89afdd49568d74d111f5/site2/docs/reference-configuration.md?plain=1#L9) to https://pulsar.apache.org/reference, it should use `/reference` to decouple with `baseDir`. This can be resolved alongside with #17499.
* [x] "API docs" in "Getting started" in https://pulsar.apache.org/download doesn't associated with a hyperlink https://github.com/apache/pulsar-site/pull/218
* [ ] Configurations links at https://pulsar.apache.org/docs/next/adaptors-kafka/#customize-pulsar-configurations section are broken
* [x] #17555
* [x] https://github.com/apache/pulsar/issues/17996
* [x] Fix dangling page developers-landing https://github.com/apache/pulsar/pull/17780

**Comment by Anonymitaet** [comment]
Thanks for raising this up! 

We (@SignorMercurio @urfreespace) are implementing [PIP 78: Generate Docs from Code Automatically](https://github.com/apache/pulsar/discussions/17328). The 1st and 3rd items in `Links` might belong to this scope.

cc @DaveDuggins @momo-jun

**Comment by labuladong** [comment]
I made a long list of broken links, so I open a new issue #17599 to discuss.

**Comment by tisonkun** [comment]
@labuladong Cool! Replace the section with a link to your issue.

**Comment by tisonkun** [comment]
@urfreespace @momo-jun it seems that `/api/cpp` is now resolved as `/api/cpp/2.10.0-SNAPSHOT` or so. Do you know which PR is related?

Although, we still need `/api/cpp/2.10.0` and so on without `-SNAPSHOT`.

**Comment by tisonkun** [comment]
Closed as all broken links are now tracked by #17599. I think we need a broken links sensor to report and guard the condition.

Other incorrect contents seem not to proceed in a short time, we can resolve them one by one - it's an endless effort.

**Comment by labuladong** [comment]
> I think we need a broken links sensor to report and guard the condition.

This is a great idea, I'll open an issue to discuss it in detail.
