### ISSUE TITLE
Tracking issue for Archive Crowdin based translation initiative

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17972]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

As discussed in https://github.com/apache/pulsar/discussions/17810, an initiative without further contributors and no maintainer to shepherd can be archived instead of left alone.

Whether CAT is a better choice or Crowdin can be added back later should be another topic. Now we archive a stalled initiative to avoid current build issues.

### Solution

* [x] https://github.com/apache/pulsar/issues/17973
* [x] https://github.com/apache/pulsar/issues/17974

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Closed as all subtasks done.
