### ISSUE TITLE
Tracking issue for Archive Ancient (Incubating) Documents

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#18144]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

I noticed that we write a lot of logic to handle ancient documents back to the incubating period on the current doc site syncing and building. It causes unnecessary maintenance burdens as well as more broken links due to different document frameworks.

### What is your suggestion?

Since those ancient documents have lower visits and most importantly, we should not make any changes to them, I propose:

- [x] #18145
- [x] #18183
- [ ] Remove build logic about those pages.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Blocked by #18174.

**Comment by tisonkun** [comment]
> Remove build logic about those pages.

@urfreespace please confirm whether there are still remaining building logics about incubating docs page. I think most are included in https://github.com/apache/pulsar-site/pull/261 and others for versions downloads/release-notes can be handled later.

**Comment by tisonkun** [comment]
Closed as all subtasks done.
