### ISSUE TITLE
Tracking Issue for Moving Source of Docs to the Site Repo

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#19064]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Mailing thread: https://lists.apache.org/thread/89wl112cflvtoyfg3l7kglr1dozsljm9

### What is your suggestion?

1. Move the website's content to the root level, then we have a first-class Docu&yarn-based JS project layout. It's more convenient and familiar to related developers.
2. Host the source of docs in the site repo (apache/pulsar-site) instead of under `site2` folder in the main repo and do content sync.

* [x] #19186
* [x] #19091
* [x] #19092
* [x] #19090
* [x] #19103
* [x] #19111
* [x] #19185
* [x] #18026
* [ ] Re-evaluate navbar. Certain topics deserve to be more prominent, like the security, use cases, and ecosystem.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Closed as all subtasks are done.

@michaeljmarshall I think the navbar issue is not strongly related to this movement; maybe I will create a new issue later.
