### ISSUE TITLE
[PIP-264] OTel should support pushdown predicate

### ISSUE THREAD

**Issue by asafm** [apache/pulsar#21123]
# Overview
Pulsar PIP-264 will introduce a filter to reduce amount of metrics exported, which is especially relevant when number of topics is large (10k - 100k per broker). This filter must be implemented inside OpenTelemetry SDK, otherwise there will be a large penalty of high memory usage, garbage collection and probably CPU, as demonstrated in this [draft PR](https://github.com/open-telemetry/opentelemetry-java/pull/5712).
The goal here is to modify OTel specifications to include a filter and subsequently implement it in OTel Java SDK.

Parent issue: https://github.com/apache/pulsar/issues/21121

# Tasks
- [ ] 🔄 [OTel specifications](https://opentelemetry.io/docs/specs/) should have a pushdown predicate
   - [x] Create issue
      - https://github.com/open-telemetry/opentelemetry-specification/issues/3324
   - [x] Garner favorable agreement from the community
   - [x] Write the proposal as PR 
      - https://github.com/open-telemetry/opentelemetry-specification/pull/3566 
    - [ ] 🔄 Work on PR to get it approved 
- [ ] OTel Java should support pushdown predicate
   - [ ] Design and approve
   - [ ] Write code with tests
   - [ ] Get PR approved

**Comment by asafm** [comment]
Still working on the PR to be approved: https://github.com/open-telemetry/opentelemetry-specification/pull/3566
Some progress have been made.

**Comment by asafm** [comment]
Still working. Mainly blocked on a question I have in this PR

**Comment by asafm** [comment]
Moved the plan into a single page plan [here](https://github.com/apache/pulsar/issues/21121)
