### ISSUE TITLE
[PIP-264] OTel should be allocation free on the collection path - asynchronous instruments

### ISSUE THREAD

**Issue by asafm** [apache/pulsar#21122]
# Goal
OpenTelemetry should be modified such that all of its asynchronous instruments would be almost allocation free,on the collection path (when MetricReader collect is invoked).

# Tasks
- [x] Learn and draft a plan for what to change
- [x] OTel Memory allocation test harness (JMH based)
- [x] Run JMH before changes
- [x] Modify the code and run JMH on it
- [x] 🔄 Submit PR and get it approved
   - https://github.com/open-telemetry/opentelemetry-java/pull/5709

**Comment by asafm** [comment]
Done
