### ISSUE TITLE
support kerberos authentication

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3491]
**Is your feature request related to a problem? Please describe.**
Currently both Zookeeper and BookKeeper could be secured by using Kerberos, It would be good to support Kerberos in Pulsar Broker and Client. 
And some user also want it.

**Describe the solution you'd like**
In Pulsar code, we already have [AuthenticationProvider](https://github.com/apache/pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProvider.java) interface in broker side, and [Authentication](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Authentication.java) interface in client side.
So the main work is to implementation these 2 interfaces and related classes above for Kerberos.

**Additional context**
sub tasks:

- [x] Mutual authentication [PIP](https://github.com/apache/pulsar/wiki/PIP-30%3A-change-authentication-provider-API-to-support-mutual-authentication)
- [x] Kerberos authenticate between client and broker #3652
- [x] Kerberos authenticate for proxy #3655
- [x] Kerberos authenticate for pulsar web resource #3653
- [x] documentation for Kerberos in Pulsar #3654

**Comment by merlimat** [comment]
@jiazhai A couple of notes:

 1. The Pulsar authn provider will have to be extended as in the current form it only supports a "single-step" authentication (and not multiple interactions between client and server). BK authn plugin is already fine.
 2. It might be worthwhile to consider implementing Kerberos on top of SASL wrapper

**Comment by jiazhai** [comment]
Thanks a lot @merlimat for the notes. 
Yes, the implementation will be on top of SASL, which is similar as how kerberos is supported in bookkeeper

**Comment by jiazhai** [comment]
would like to close this issue. since the main work is done here.
