### ISSUE TITLE
PIP-34 New subscription type Key_Shared

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#4077]
There are many aspects to be covered for [PIP-34](https://github.com/apache/pulsar/wiki/PIP-34%3A-Add-new-subscribe-type-Key_Failover), this is a task list tracker for this PIP

**Tasks**

- [x] Core implementation #4079
- [x] Broker level flag to enable or disable this feature #4120
- [x] Integration tests #4352
- [x] Non persistent dispatcher #4462
- [x] Documentation  #4079
- [ ] Policy specify without message key  #6553
- [x] Batch message #4435
- [x] Redelivery ordering guarantee #4406 
- [ ] dispatch messages to new consumer after exist consumer ack all messages dispatched #6554
- [ ] send hash ring change events to consumers  #6555
- [x] Reader support for sticky key range [#5928]
- [ ] Expose key shared consumer selector range in API [#5752]

**Comment by sijie** [comment]
@codelipenghui I added an issue #4169 for the requirements of supporting sticky consumers in Key_Shared subscription.

**Comment by sijie** [comment]
@codelipenghui I added one item to the key_shared subscription - adding the support for a sticky-range reader. The requirement is coming from Flink connector. We need to read a sub-stream (a range) from a given message id. This should be pretty straightforward to add since a reader is an exclusive non-durable subscription. So we can just seek to the provided message id and filter the messages based on the key/value.

@yjshen can chime in for more requirements for Flink connector.

**Comment by david-streamlio** [comment]
Is there an ETA for this PIP?

**Comment by sijie** [comment]
@david-streamlio the core functionalities for this PIP are already done. It has been used in quite bunch of productions. the left items are more or fewer enhancements.

@codelipenghui I think we should consider moving the items that are not done into a separate issue for tracking, close this issue and mark BP-38 as done.

**Comment by codelipenghui** [comment]
@sijie I have added new issues for the items that are not done. So close this issue now.

**Comment by sijie** [comment]
@codelipenghui thank you
