### ISSUE TITLE
[WIP][pulsar-admin-tools] Support delete all data associated with a cluster

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar#8134]
This issue is related to #8133 

- [x] #8244 Add a integration test for deleting cluster's all data and metadata
- [x] #8167 #8258  Delete the schema ledgers, see #8136 
- [x] #8244  Delete cluster's all data and metadata when broker is not alive.
