### ISSUE TITLE
[PIP-50] Package management service implement

### ISSUE THREAD

**Issue by zymap** [apache/pulsar#8676]
PIP-50 implementation:
- [x] Introduce the packages management interface API #8669  #8680 
- [x] Support bookkeeper storage for the packages management storage #8744 
- [x] Introduce REST APIs for the package management service #8764 #8858 
- [x] Add client-side APIs for the package management service #8816 #8817 
- [x] Add integration tests for this service #8876 
- [x] Add auth related changes #8893 
- [x] Support the package download command in Functions #8973 #8987 #8988
- [x] Add document for the package service #8896 #9071 

PIP: https://github.com/apache/pulsar/wiki/PIP-50%3A-Package-Management

**Comment by zymap** [comment]
All the PR is merged. Close this issue.
